// ============================================================================
//  File: framework.h
//  Module: Obsidian.Runtime
//  Purpose:
//      Central include file for Windows system headers and C runtime headers.
//      This file is generated by Visual Studio and forms part of the default
//      Win32 application scaffolding.
//
//  Why we KEEP this file:
//      - It ensures consistent Windows header inclusion across the project.
//      - It defines WIN32_LEAN_AND_MEAN to reduce compile time and avoid
//        unnecessary header bloat.
//      - It is required for WinMain, window creation, message loops, and
//        all Win32 API calls used by the runtime.
//      - Removing or modifying this file incorrectly WILL break the build.
//
//  Notes:
//      - We do NOT delete or rename this file.
//      - We do NOT remove WIN32_LEAN_AND_MEAN.
//      - We do NOT remove <windows.h>.
//      - This file remains untouched until the engine has its own platform layer.
// ============================================================================

#pragma once

#include "targetver.h"          // Defines the minimum Windows SDK version

#define WIN32_LEAN_AND_MEAN     // Exclude rarely-used APIs from <windows.h>

// ---------------------------------------------------------------------------
//  Windows Header Files
// ---------------------------------------------------------------------------
#include <windows.h>            // Core Win32 API (window creation, messages, etc.)

// ---------------------------------------------------------------------------
//  C Runtime Header Files
// ---------------------------------------------------------------------------
#include <stdlib.h>             // Standard library functions (malloc, free, etc.)
#include <malloc.h>             // Memory allocation helpers
#include <memory.h>             // memset, memcpy, memmove
#include <tchar.h>              // Unicode/ANSI portable text macros
