// ============================================================================
//  File: Obsidian.Runtime.h
//  Module: Obsidian.Runtime
//  Purpose:
//      Default project header generated by Visual Studio for the runtime
//      executable. This header is intended to hold runtime‑specific
//      declarations, helper functions, and engine entry points.
//
//  Why we KEEP this file:
//      - It is part of the default Win32 application scaffolding.
//      - It is included by Obsidian.Runtime.cpp.
//      - It provides a clean place to add runtime‑level declarations later.
//      - Removing or renaming it can break the build or resource compiler.
//
//  Notes:
//      - Currently contains only a reference to Resource.h.
//      - We do NOT modify or remove this include.
//      - We will expand this file later when the runtime gains engine‑level
//        functions (initialization, shutdown, command‑line parsing, etc.).
// ============================================================================

#pragma once

#include "Resource.h"   // Resource identifiers for icons, dialogs, version info
